// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_TASK_TYPE_UNSPECIFIED TaskType = 0
	TaskType_TASK_TYPE_MAP         TaskType = 1
	TaskType_TASK_TYPE_REDUCE      TaskType = 2
	TaskType_TASK_TYPE_WAIT        TaskType = 3
	TaskType_TASK_TYPE_EXIT        TaskType = 4
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNSPECIFIED",
		1: "TASK_TYPE_MAP",
		2: "TASK_TYPE_REDUCE",
		3: "TASK_TYPE_WAIT",
		4: "TASK_TYPE_EXIT",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED": 0,
		"TASK_TYPE_MAP":         1,
		"TASK_TYPE_REDUCE":      2,
		"TASK_TYPE_WAIT":        3,
		"TASK_TYPE_EXIT":        4,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_service_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_proto_service_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

type FileStatus int32

const (
	FileStatus_FILE_STATUS_UNSPECIFIED   FileStatus = 0
	FileStatus_FILE_STATUS_NOT_PROCESSED FileStatus = 1
	FileStatus_FILE_STATUS_IN_PROGRESS   FileStatus = 2
	FileStatus_FILE_STATUS_PROCESSED     FileStatus = 3
)

// Enum value maps for FileStatus.
var (
	FileStatus_name = map[int32]string{
		0: "FILE_STATUS_UNSPECIFIED",
		1: "FILE_STATUS_NOT_PROCESSED",
		2: "FILE_STATUS_IN_PROGRESS",
		3: "FILE_STATUS_PROCESSED",
	}
	FileStatus_value = map[string]int32{
		"FILE_STATUS_UNSPECIFIED":   0,
		"FILE_STATUS_NOT_PROCESSED": 1,
		"FILE_STATUS_IN_PROGRESS":   2,
		"FILE_STATUS_PROCESSED":     3,
	}
)

func (x FileStatus) Enum() *FileStatus {
	p := new(FileStatus)
	*p = x
	return p
}

func (x FileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_service_proto_enumTypes[1].Descriptor()
}

func (FileStatus) Type() protoreflect.EnumType {
	return &file_proto_service_proto_enumTypes[1]
}

func (x FileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileStatus.Descriptor instead.
func (FileStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskType      TaskType               `protobuf:"varint,1,opt,name=task_type,json=taskType,proto3,enum=proto.TaskType" json:"task_type,omitempty"`
	InputPath     string                 `protobuf:"bytes,2,opt,name=input_path,json=inputPath,proto3" json:"input_path,omitempty"`
	ReduceIndex   int32                  `protobuf:"varint,3,opt,name=reduce_index,json=reduceIndex,proto3" json:"reduce_index,omitempty"`
	NReduce       int32                  `protobuf:"varint,4,opt,name=n_reduce,json=nReduce,proto3" json:"n_reduce,omitempty"`
	ReducePaths   []string               `protobuf:"bytes,5,rep,name=reduce_paths,json=reducePaths,proto3" json:"reduce_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskResponse) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *GetTaskResponse) GetInputPath() string {
	if x != nil {
		return x.InputPath
	}
	return ""
}

func (x *GetTaskResponse) GetReduceIndex() int32 {
	if x != nil {
		return x.ReduceIndex
	}
	return 0
}

func (x *GetTaskResponse) GetNReduce() int32 {
	if x != nil {
		return x.NReduce
	}
	return 0
}

func (x *GetTaskResponse) GetReducePaths() []string {
	if x != nil {
		return x.ReducePaths
	}
	return nil
}

type ReportMapDoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	InputPath     string                 `protobuf:"bytes,2,opt,name=input_path,json=inputPath,proto3" json:"input_path,omitempty"`
	ReducePaths   []string               `protobuf:"bytes,3,rep,name=reduce_paths,json=reducePaths,proto3" json:"reduce_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportMapDoneRequest) Reset() {
	*x = ReportMapDoneRequest{}
	mi := &file_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportMapDoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportMapDoneRequest) ProtoMessage() {}

func (x *ReportMapDoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportMapDoneRequest.ProtoReflect.Descriptor instead.
func (*ReportMapDoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReportMapDoneRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReportMapDoneRequest) GetInputPath() string {
	if x != nil {
		return x.InputPath
	}
	return ""
}

func (x *ReportMapDoneRequest) GetReducePaths() []string {
	if x != nil {
		return x.ReducePaths
	}
	return nil
}

type ReportReduceDoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ReduceIndex   int32                  `protobuf:"varint,2,opt,name=reduce_index,json=reduceIndex,proto3" json:"reduce_index,omitempty"`
	OutputPath    string                 `protobuf:"bytes,3,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportReduceDoneRequest) Reset() {
	*x = ReportReduceDoneRequest{}
	mi := &file_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportReduceDoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportReduceDoneRequest) ProtoMessage() {}

func (x *ReportReduceDoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportReduceDoneRequest.ProtoReflect.Descriptor instead.
func (*ReportReduceDoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReportReduceDoneRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReportReduceDoneRequest) GetReduceIndex() int32 {
	if x != nil {
		return x.ReduceIndex
	}
	return 0
}

func (x *ReportReduceDoneRequest) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusRequest) Reset() {
	*x = JobStatusRequest{}
	mi := &file_proto_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusRequest) ProtoMessage() {}

func (x *JobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusRequest.ProtoReflect.Descriptor instead.
func (*JobStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{6}
}

type JobStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Done            bool                   `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	MapTotal        int32                  `protobuf:"varint,2,opt,name=map_total,json=mapTotal,proto3" json:"map_total,omitempty"`
	MapCompleted    int32                  `protobuf:"varint,3,opt,name=map_completed,json=mapCompleted,proto3" json:"map_completed,omitempty"`
	ReduceTotal     int32                  `protobuf:"varint,4,opt,name=reduce_total,json=reduceTotal,proto3" json:"reduce_total,omitempty"`
	ReduceCompleted int32                  `protobuf:"varint,5,opt,name=reduce_completed,json=reduceCompleted,proto3" json:"reduce_completed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobStatusResponse) Reset() {
	*x = JobStatusResponse{}
	mi := &file_proto_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusResponse) ProtoMessage() {}

func (x *JobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusResponse.ProtoReflect.Descriptor instead.
func (*JobStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *JobStatusResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *JobStatusResponse) GetMapTotal() int32 {
	if x != nil {
		return x.MapTotal
	}
	return 0
}

func (x *JobStatusResponse) GetMapCompleted() int32 {
	if x != nil {
		return x.MapCompleted
	}
	return 0
}

func (x *JobStatusResponse) GetReduceTotal() int32 {
	if x != nil {
		return x.ReduceTotal
	}
	return 0
}

func (x *JobStatusResponse) GetReduceCompleted() int32 {
	if x != nil {
		return x.ReduceCompleted
	}
	return 0
}

var File_proto_service_proto protoreflect.FileDescriptor

const file_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x13proto/service.proto\x12\x05proto\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"-\n" +
	"\x0eGetTaskRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\xbf\x01\n" +
	"\x0fGetTaskResponse\x12,\n" +
	"\ttask_type\x18\x01 \x01(\x0e2\x0f.proto.TaskTypeR\btaskType\x12\x1d\n" +
	"\n" +
	"input_path\x18\x02 \x01(\tR\tinputPath\x12!\n" +
	"\freduce_index\x18\x03 \x01(\x05R\vreduceIndex\x12\x19\n" +
	"\bn_reduce\x18\x04 \x01(\x05R\anReduce\x12!\n" +
	"\freduce_paths\x18\x05 \x03(\tR\vreducePaths\"u\n" +
	"\x14ReportMapDoneRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"input_path\x18\x02 \x01(\tR\tinputPath\x12!\n" +
	"\freduce_paths\x18\x03 \x03(\tR\vreducePaths\"z\n" +
	"\x17ReportReduceDoneRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12!\n" +
	"\freduce_index\x18\x02 \x01(\x05R\vreduceIndex\x12\x1f\n" +
	"\voutput_path\x18\x03 \x01(\tR\n" +
	"outputPath\"/\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x12\n" +
	"\x10JobStatusRequest\"\xb7\x01\n" +
	"\x11JobStatusResponse\x12\x12\n" +
	"\x04done\x18\x01 \x01(\bR\x04done\x12\x1b\n" +
	"\tmap_total\x18\x02 \x01(\x05R\bmapTotal\x12#\n" +
	"\rmap_completed\x18\x03 \x01(\x05R\fmapCompleted\x12!\n" +
	"\freduce_total\x18\x04 \x01(\x05R\vreduceTotal\x12)\n" +
	"\x10reduce_completed\x18\x05 \x01(\x05R\x0freduceCompleted*v\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rTASK_TYPE_MAP\x10\x01\x12\x14\n" +
	"\x10TASK_TYPE_REDUCE\x10\x02\x12\x12\n" +
	"\x0eTASK_TYPE_WAIT\x10\x03\x12\x12\n" +
	"\x0eTASK_TYPE_EXIT\x10\x04*\x80\x01\n" +
	"\n" +
	"FileStatus\x12\x1b\n" +
	"\x17FILE_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19FILE_STATUS_NOT_PROCESSED\x10\x01\x12\x1b\n" +
	"\x17FILE_STATUS_IN_PROGRESS\x10\x02\x12\x19\n" +
	"\x15FILE_STATUS_PROCESSED\x10\x032\x88\x02\n" +
	"\x12CoordinatorService\x128\n" +
	"\aGetTask\x12\x15.proto.GetTaskRequest\x1a\x16.proto.GetTaskResponse\x128\n" +
	"\rReportMapDone\x12\x1b.proto.ReportMapDoneRequest\x1a\n" +
	".proto.Ack\x12>\n" +
	"\x10ReportReduceDone\x12\x1e.proto.ReportReduceDoneRequest\x1a\n" +
	".proto.Ack\x12>\n" +
	"\tJobStatus\x12\x17.proto.JobStatusRequest\x1a\x18.proto.JobStatusResponseB\x15Z\x13Desktop/mr/proto;pbb\x06proto3"

var (
	file_proto_service_proto_rawDescOnce sync.Once
	file_proto_service_proto_rawDescData []byte
)

func file_proto_service_proto_rawDescGZIP() []byte {
	file_proto_service_proto_rawDescOnce.Do(func() {
		file_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)))
	})
	return file_proto_service_proto_rawDescData
}

var file_proto_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_service_proto_goTypes = []any{
	(TaskType)(0),                   // 0: proto.TaskType
	(FileStatus)(0),                 // 1: proto.FileStatus
	(*KeyValue)(nil),                // 2: proto.KeyValue
	(*GetTaskRequest)(nil),          // 3: proto.GetTaskRequest
	(*GetTaskResponse)(nil),         // 4: proto.GetTaskResponse
	(*ReportMapDoneRequest)(nil),    // 5: proto.ReportMapDoneRequest
	(*ReportReduceDoneRequest)(nil), // 6: proto.ReportReduceDoneRequest
	(*Ack)(nil),                     // 7: proto.Ack
	(*JobStatusRequest)(nil),        // 8: proto.JobStatusRequest
	(*JobStatusResponse)(nil),       // 9: proto.JobStatusResponse
}
var file_proto_service_proto_depIdxs = []int32{
	0, // 0: proto.GetTaskResponse.task_type:type_name -> proto.TaskType
	3, // 1: proto.CoordinatorService.GetTask:input_type -> proto.GetTaskRequest
	5, // 2: proto.CoordinatorService.ReportMapDone:input_type -> proto.ReportMapDoneRequest
	6, // 3: proto.CoordinatorService.ReportReduceDone:input_type -> proto.ReportReduceDoneRequest
	8, // 4: proto.CoordinatorService.JobStatus:input_type -> proto.JobStatusRequest
	4, // 5: proto.CoordinatorService.GetTask:output_type -> proto.GetTaskResponse
	7, // 6: proto.CoordinatorService.ReportMapDone:output_type -> proto.Ack
	7, // 7: proto.CoordinatorService.ReportReduceDone:output_type -> proto.Ack
	9, // 8: proto.CoordinatorService.JobStatus:output_type -> proto.JobStatusResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_service_proto_init() }
func file_proto_service_proto_init() {
	if File_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_proto_goTypes,
		DependencyIndexes: file_proto_service_proto_depIdxs,
		EnumInfos:         file_proto_service_proto_enumTypes,
		MessageInfos:      file_proto_service_proto_msgTypes,
	}.Build()
	File_proto_service_proto = out.File
	file_proto_service_proto_goTypes = nil
	file_proto_service_proto_depIdxs = nil
}
